### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by nicholasxuu** [sensorsdata/react-native-sensors-analytics#10]
react-native版本号 0.59.10

按照官方文档安装完第三部分后，打包尝试测试，build失败：

```
/node_modules/@sensors.data/react-native-sensors-analytics/ios/RNSensorsAnalyticsModule.h
```
里面的`#import <React/RCTBridgeModule.h> `报错：

```
'React/RCTBridgeModule.h' file not found
```

**Comment by 994914624** [comment]
可以用 Xcode 打开项目：
①选中当前工程 --> Build Settings -->  Search Paths -->  Header Search Paths，添加：$(SRCROOT)/../node_modules/react-native/React

②选中当前工程 --> 找到 Build Phases --> Target Dependencies --> 点击 + --> 添加 React 依赖后，clean & build 试一下。 @nicholasxuu 如果未能解决，请留下你的联系方式，谢谢。

**Comment by nicholasxuu** [comment]
@994914624 
那个方法没有用，之前装react-native-wechat也遇到过，也试过这种方法，没用。后来用他们master branch里的podspec安装成功的。

能否写个podspec用来安装？

想问一下这个repo里的代码有用吗？我把相关的东西都从当前工程项目里删了，只从pod里安装了SensorsAnalyticsSDK（还是1.11.12版的），配合[官方安装文档](https://www.sensorsdata.cn/manual/sdk_reactnative.html)里的安装方法，build成功。
*更新：测试了一下，使用成功，$AppStart, $AppClick, $AppEnd都好的。

而且文档里的启动代码也用了很多这个repo里没有的东西，比如`SAConfigOptions`。

然后，还出现一些warning，比如`'sharedInstanceWithConfig:' is deprecated: 已过时，请使用 + (void)startWithConfigOptions: 方法进行初始化`，`sharedInstanceWithConfig`不在这个repo里，在SensorsAnalyticsSDK v1.11.12里也是deprecated。[安装文档](https://www.sensorsdata.cn/manual/sdk_reactnative.html)是否需要更新了？

**Comment by 994914624** [comment]
@nicholasxuu 
1. podspec 我们这边看一下。
2. 当前库(repo) 是封装了 SDK 的一些原生接口，给 RN 中代码埋点用的，如果你不集成此模块，就无法在  RN 中使用自定义代码埋点。
3. 新版本 SDK 增加了新的初始化接口，旧的接口还能使用，我们稍后更新一下文档。

**Comment by caojianfeng** [comment]
podspec++

**Comment by nicholasxuu** [comment]
@994914624 
我瞎写的podspec，跑起来了。主要是俩dependency。
```
Pod::Spec.new do |s|
  s.name         = "RNSensorsAnalyticsModule"
  s.version      = "1.9.10"
  s.summary      = "aaa"
  s.description  = <<-DESC
  bbb
   DESC
  s.author       = { "weflex" => "" }
  s.homepage     = "https://github.com/"
  s.license      = "MIT"
  s.platform     = :ios, "10.0"
  s.source       = { :git => "https://github.com/nicholasxuu/react-native-sensors-analytics.git", :tag => "master" }
  s.source_files  = "ios/*.{h,m}"
  s.framework    = 'SystemConfiguration'
  s.dependency "React"
  s.dependency "SensorsAnalyticsSDK"
end
```
放项目的跟目录。
要用的话把version, summery, description之类的更新一下。（记得要更新source为你们自己的）

安装方法就是给ios项目的Podfile里加上：
```
pod "RNSensorsAnalyticsModule", :path => '../node_modules/@sensors.data/react-native-sensors-analytics'
```

然后安装文档也要更新一点点东西，
官方文档说，在AppDelegate.m里，用`import <SensorsAnalyticsSDK.h>`。这样的话，会调用了这个包里的`SensorsAnalyticsSDK.h`，而不是`SensorsAnalyticsSDK`包里的`SensorsAnalyticsSDK.h`，导致那些init的代码失败。
所以，需要把文档里的`import <SensorsAnalyticsSDK.h>`改为`#import <SensorsAnalyticsSDK/SensorsAnalyticsSDK.h>`

求尽早更新，不然我得fork成自己的版本npm publish了才能用。

**Comment by nicholasxuu** [comment]
PR: https://github.com/sensorsdata/react-native-sensors-analytics/pull/12/files

**Comment by songxiaoliang** [comment]
@nicholasxuu 一直提示No visible @interface for 'SensorsAnalyticsSDK' ,有遇到吗?

**Comment by 994914624** [comment]
一直提示No visible @interface for 'SensorsAnalyticsSDK' ,有遇到吗?
------------------------------------------------------------------
@songxiaoliang 麻烦检查一下集成步骤，按集成步骤再走一遍。若遇到问题，麻烦描述并贴出一下具体的问题。

**Comment by 994914624** [comment]
v1.1.1 已加上 podspec 感谢 @nicholasxuu 提 PR

**Comment by nicholasxuu** [comment]
@songxiaoliang 旧文档有点问题，新文档可能更新了，引用的包不对，需要`import <SensorsAnalyticsSDK/SensorsAnalyticsSDK.h>`
