### ISSUE TITLE
warning No podspec file was found. under RN60

### ISSUE THREAD

**Issue by caojianfeng** [sensorsdata/react-native-sensors-analytics#11]
现在RN0.60 提供了autolink功能，如果没有podspec就auto不了就只能手动了。

[!] use_native_modules! skipped the react-native dependency '@sensors.data/react-native-sensors-analytics'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a
    package.json driven podspec. See https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**Comment by songxiaoliang** [comment]
@caojianfeng 能方便加下微信吗,遇到点问题

**Comment by 994914624** [comment]
v1.1.1 加上 podspec
