### ISSUE TITLE
安卓是否不能自定义打点？

### ISSUE THREAD

**Issue by nicholasxuu** [sensorsdata/react-native-sensors-analytics#13]
安卓里显示`NativeModules.RNSensorsAnalyticsModule`是不存在的。

安卓是否支持自定义打点？

**Comment by nicholasxuu** [comment]
找到了。

`MainApplication.java` 的 `getPackages()`里需要加上`new RNSensorsAnalyticsPackage()`

文档里没说，能否注明一下？

**Comment by 994914624** [comment]
执行 react-native link @sensors.data/react-native-sensors-analytics 命令，会自动加上 new RNSensorsAnalyticsPackage(), 这行代码 @nicholasxuu
