### ISSUE TITLE
最新版本的报错

### ISSUE THREAD

**Issue by mvpdream** [sensorsdata/react-native-sensors-analytics#14]
![image](https://user-images.githubusercontent.com/16203724/67918785-c057d480-fbd8-11e9-883b-10f5b3243288.png)

**Comment by mvpdream** [comment]
@994914624

**Comment by 994914624** [comment]
@mvpdream 集成步骤执行 cd ios && pod install 了没有？具体怎么使用的，麻烦截图示意一下。

**Comment by mvpdream** [comment]
pod insatall 执行过了 link也执行了

**Comment by mvpdream** [comment]
pod install 执行过了 react-native link 也执行了,升级这个库之前是好的,更新完之后就报这个了

**Comment by mvpdream** [comment]
@994914624

**Comment by 994914624** [comment]
@mvpdream 加我扣扣 1691850993

**Comment by 994914624** [comment]
@mvpdream RN 版本号为多少？
