### ISSUE TITLE
建议更新 SensorsAnalyticsSDK/SensorsAnalyticsSDK.m文件中的UIWebview

### ISSUE THREAD

**Issue by songxiaoliang** [sensorsdata/react-native-sensors-analytics#16]
在SDK中使用了UIWebview, 苹果最新建议使用WKWebview, 届时会对使用UIWebview的情况警告, 我们目前在全面替换, 建议更新.

代码位置如下: 
SensorsAnalyticsSDK/SensorsAnalyticsSDK.m:  UIWebView* webView.....

**Comment by dev-dylan** [comment]
您好，您反馈的禁用 UIWebView 的需求在 iOS SDK 最新版本 v2.0.1 已提供，您可以将 iOS SDK 版本升级至最新版本后使用此功能。
具体使用方法可参考神策官网  [ iOS SDK 集成文档](https://manual.sensorsdata.cn/sa/latest/tech_sdk_client_ios_super-7541828.html#id-.iOS%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BDv1.15-%E9%A2%84%E7%BC%96%E8%AF%91%E5%AE%8F%E9%85%8D%E7%BD%AESDK%E7%89%B9%E6%80%A7)。
您也可以查看  [iOS SDK release](https://github.com/sensorsdata/sa-sdk-ios/releases) 了解 iOS SDK 近期更新内容。

**Comment by songxiaoliang** [comment]
@dev-dylan 谢谢, 我们会及时更新
