### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

### ISSUE THREAD

**Issue by chengkaigithub** [sensorsdata/react-native-sensors-analytics#17]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

请问如何去掉UIWebView？

**Comment by chengkaigithub** [comment]
找到了文档描述：
https://manual.sensorsdata.cn/sa/latest/sdk-api-ios-1573998.html

**Comment by viewerw** [comment]
> 找到了文档描述：
> https://manual.sensorsdata.cn/sa/latest/sdk-api-ios-1573998.html

@chengkaigithub 请问如何更新podfile,我这样写报错了
pod 'RNSensorsAnalyticsModule', :path => '../node_modules/sensorsdata-analytics-react-native',:subspecs => ['DISABLE_UIWEBVIEW']

**Comment by dev-dylan** [comment]
> > 找到了文档描述：
> > https://manual.sensorsdata.cn/sa/latest/sdk-api-ios-1573998.html
> 
> @chengkaigithub 请问如何更新podfile,我这样写报错了
> pod 'RNSensorsAnalyticsModule', :path => '../node_modules/sensorsdata-analytics-react-native',:subspecs => ['DISABLE_UIWEBVIEW']

您可以在项目中的 SensorsAnalyticsSDK 的 build settings 选项卡中搜索 macro 关键字，然后在 Preprocessing Macro 中添加 `SENSORS_ANALYTICS_DISABLE_UIWEBVIEW=1` 来禁用 UIWebView 相关功能。详细步骤如下图：

![QQ20200801-103325](https://user-images.githubusercontent.com/9349177/89092231-78254700-d3e2-11ea-9614-442cffda6736.png)

**Comment by viewerw** [comment]
![image](https://user-images.githubusercontent.com/23723466/89141978-bb192300-d578-11ea-8ccf-fcd842364a42.png)
我这边这样改了，但是苹果的邮件还是提示问题

**Comment by dev-dylan** [comment]
> ![image](https://user-images.githubusercontent.com/23723466/89141978-bb192300-d578-11ea-8ccf-fcd842364a42.png)
> 我这边这样改了，但是苹果的邮件还是提示问题

你也可以通过在项目 node_module 中的 sensorsdata-analytics-react-native 文件夹，修改 RNSensorsAnalyticsModule.podspec 的内容来禁用 UIWebView 功能。详细修改如下图：
![image](https://user-images.githubusercontent.com/9349177/89276407-344a7000-d676-11ea-9f72-59dacd3c0cac.png)
![image](https://user-images.githubusercontent.com/9349177/89276464-46c4a980-d676-11ea-9ec8-21dd088fe0c2.png)

如果以上方案还是没有解决你的问题，你也可以在神策对接群或神策开源交流群中找技术顾问同学帮忙解决问题。

**Comment by viewerw** [comment]
> > ![image](https://user-images.githubusercontent.com/23723466/89141978-bb192300-d578-11ea-8ccf-fcd842364a42.png)
> > 我这边这样改了，但是苹果的邮件还是提示问题
> 
> 你也可以通过在项目 node_module 中的 sensorsdata-analytics-react-native 文件夹，修改 RNSensorsAnalyticsModule.podspec 的内容来禁用 UIWebView 功能。详细修改如下图：
> ![image](https://user-images.githubusercontent.com/9349177/89276407-344a7000-d676-11ea-9f72-59dacd3c0cac.png)
> ![image](https://user-images.githubusercontent.com/9349177/89276464-46c4a980-d676-11ea-9ec8-21dd088fe0c2.png)
> 
> 如果以上方案还是没有解决你的问题，你也可以在神策对接群或神策开源交流群中找技术顾问同学帮忙解决问题。

我尝试后成功了，你的代码少了个引号，应该为：` s.dependency   "SensorsAnalyticsSDK/DISABLE_UIWEBVIEW", ">= 1.11.15"`
但是有个问题，每次yarn 更新依赖后，都要手动改
