### ISSUE TITLE
假如使用自建的采集地址，应该怎么配置

### ISSUE THREAD

**Issue by kfypmqqw** [sensorsdata/react-native-sensors-analytics#20]
final String SA_SERVER_URL = "https://xxxx.com/log.gif";

使用以上设置之后，启动不报错 ，在onPress调用   sensors.track('RN_AddToFav', {ProductID: 123456, UserLevel: 'VIP'});  也没有任何日志输出，请问应该任何配置？

**Comment by cr1106** [comment]
您需要开启日志输出，具体配置和集成可参考 https://manual.sensorsdata.cn/sa/latest/tech_sdk_client_three_react-7549534.html#id-.ReactNativev1.15-初始化SDK.1
