### ISSUE TITLE
神策如何关闭android_id获取，或者有方法设置神策获取的时机吗

### ISSUE THREAD

**Issue by shengbowen** [sensorsdata/react-native-sensors-analytics#23]
现在因为应用市场禁止在 用户授权隐私之前，获取android_id。  目前检测到神策会获取andrioid导致审核不通过

**Comment by cr1106** [comment]
![image](https://user-images.githubusercontent.com/4122965/159469566-4914f0ff-d7ac-4325-8e74-03d2d1bb3e9f.png)

**Comment by liuweiqiang2016** [comment]
v2.2.5 级以上版本支持 RN 插件延迟初始化，用户同意隐私协议后，再初始化 SDK
