### ISSUE TITLE
index.d.ts文件有一些ts问题

### ISSUE THREAD

**Issue by longtoken** [sensorsdata/react-native-sensors-analytics#25]
index.d.ts文件
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/20136535/174972334-ab46ac64-0045-4266-a448-e0231133bea8.png">

17行：max_cache_size:long,//最大缓存数，默认 32*1024*1024
long需要改成number
28行：declare enum SAAutoTrackType {
由于文件里没有export，SAAutoTrackType无法使用import导入
304行：   export function trackAppInstall(properties: PropertiesObjectType | null)
319行：    export function bind(key: string, value: string);
327行：     export function unbind(key: string, value: string);
334行：     export function init(config: Config);
需要增加返回值

另外官网的文档写着的调用方式只传了server_url、auto_track两个参数，所以类型Config其他不需要的参数需要加上表示可选的问号(?)。如果参数都是需要的，文档能改下调用方式吗。
<img width="916" alt="image" src="https://user-images.githubusercontent.com/20136535/174971011-44ed33f5-55f6-45d9-83be-da339d98becb.png">

**Comment by cr1106** [comment]
感谢反馈，我们会尽快修改

**Comment by cr1106** [comment]
SAAutoTrackType 参考文档可以正常导入的

**Comment by cr1106** [comment]
init 所有参数都是可选的，包括 config

**Comment by longtoken** [comment]
> SAAutoTrackType 参考文档可以正常导入的

不行哦，直接使用会报错
<img width="970" alt="image" src="https://user-images.githubusercontent.com/20136535/175880451-3a853b78-0ad9-4749-8f4b-3fc5b43f7b77.png">

**Comment by cr1106** [comment]
![image](https://user-images.githubusercontent.com/4122965/175909941-ff99a5be-78a8-4c9c-8900-1c998a7cccba.png)

![image](https://user-images.githubusercontent.com/4122965/175909843-1738fa68-cc0b-4a36-8252-3a899985a499.png)
![image](https://user-images.githubusercontent.com/4122965/175910001-d55371b1-7a68-4072-bf9a-6b9055f54412.png)

这边测试是可以的

**Comment by longtoken** [comment]
> ![image](https://user-images.githubusercontent.com/4122965/175909941-ff99a5be-78a8-4c9c-8900-1c998a7cccba.png)
> 
> ![image](https://user-images.githubusercontent.com/4122965/175909843-1738fa68-cc0b-4a36-8252-3a899985a499.png) ![image](https://user-images.githubusercontent.com/4122965/175910001-d55371b1-7a68-4072-bf9a-6b9055f54412.png)
> 
> 这边测试是可以的

使用的typescript版本是多少？看看 tsc -v

**Comment by longtoken** [comment]
> init 所有参数都是可选的，包括 config

参数都是可选的话，那加一个Partial吧？
export function init(config: Partial\<Config\>):void

**Comment by longtoken** [comment]
> > init 所有参数都是可选的，包括 config
> 
> 参数都是可选的话，那加一个Partial吧？ export function init(config: Partial<Config>):void

**Comment by cr1106** [comment]
> > ![image](https://user-images.githubusercontent.com/4122965/175909941-ff99a5be-78a8-4c9c-8900-1c998a7cccba.png)
> > ![image](https://user-images.githubusercontent.com/4122965/175909843-1738fa68-cc0b-4a36-8252-3a899985a499.png) ![image](https://user-images.githubusercontent.com/4122965/175910001-d55371b1-7a68-4072-bf9a-6b9055f54412.png)
> > 这边测试是可以的
> 
> 使用的typescript版本是多少？看看 tsc -v

ts 里确实是提示错误，但不影响使用，后面再优化下 ts 申明

**Comment by cr1106** [comment]
已发版 2.3.0
